import type { Metadata } from "next";
import "./globals.css";
import "../../public/styles/fonts.css";
import ThemeProvider from "@/theme";
import EmotionProvider from "@/emotion/EmotionProvider";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body>
        <EmotionProvider>
          <ThemeProvider>{children}</ThemeProvider>
        </EmotionProvider>
      </body>
    </html>
  );
}
